---
# DNF packages to install
cli_dnf_packages:
  - alacritty
  - autorandr
  - bat
  - chromium
  - conky
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - dunst
  - eza
  - fd-find
  - feh
  - firefox
  - fish
  - fzf
  - gh
  - git-delta
  - ghostty
  - helm
  - htop
  - i3
  - ImageMagick
  - jq
  - keepassxc
  - kubectl
  - neofetch
  - neovim
  - picom
  - polybar
  - python3-pip
  - ripgrep
  - rofi
  - rust
  - rustfmt
  - starship
  - sublime-text
  - terraform
  - tig
  - opentofu
  - tmux
  - golang
  - golang-x-tools-gopls
  - unzip
  - xclip

# Fish plugins to install via fisher
fish_plugins:
  - gazorby/fish-abbreviation-tips
  - jethrokuan/z
  - jorgebucaran/nvm.fish
  - PatrickF1/fzf.fish

# Node.js versions to install via nvm.fish
node_versions:
  - 18.16.0
  - latest

# Bun packages to install globally
bun_packages:
  - gatsby-cli@5.11.0
  - resume-cli@3.0.8

# GitHub CLI extensions to install
gh_extensions:
  - dlvhdr/gh-dash

fedora_repositories:
  - name: docker-ce-stable
    description: Docker CE Stable - $basearch
    url: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpg_url: https://download.docker.com/linux/fedora/gpg
    gpg_check: true

  - name: hashicorp
    description: Hashicorp Stable - $basearch
    url: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpg_url: https://apt.releases.hashicorp.com/gpg
    gpg_check: true

  - name: Kubernetes
    description: Kubernetes
    url: https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
    gpg_url: https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key
    gpg_check: true

  - name: sublime-text
    description: Sublime Text x86_64 - stable
    url: https://download.sublimetext.com/rpm/stable/x86_64
    gpg_url: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    gpg_check: true

copr_repositories:
  - name: atim/starship
    creates: _copr:copr.fedorainfracloud.org:atim:starship.repo
  - name: scottames/ghostty
    creates: _copr:copr.fedorainfracloud.org:scottames:ghostty.repo
  - name: "@go-sig/golang-rawhide"
    creates: _copr:copr.fedorainfracloud.org:group_go-sig:golang-rawhide.repo
