---
add_python_versions:
  - 3.12

packages:
  - virtualfish                           # https://github.com/justinmayer/virtualfish
  - yt-dlp                                # https://github.com/yt-dlp/yt-dlp
  - tldr                                  # 

fedora_packages:
  - pywal                                 # https://github.com/dylanaraps/pywal
  - "maestral[gui]"                       # https://maestral.app/ - Dropbox client

mac_packages: []