---
fedora_repositories:
  - name: sublime-text
    description: Sublime Text x86_64 - stable
    url: https://download.sublimetext.com/rpm/stable/x86_64
    gpg_url: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    gpg_check: true

sublime_packages:
  - name: "https://github.com/clifford-github/sublime-ansible.git"
  - name: "https://github.com/jisaacks/GitGutter.git"
  - name: "https://github.com/sublimelsp/LSP.git"
    version: "main"
  - name: "https://github.com/sublimelsp/LSP-file-watcher-chokidar.git" 
    version: "main"
  - name: "https://github.com/sublimelsp/LSP-terraform.git"
    version: "main"
  - name: "https://github.com/sublimelsp/LSP-pyright.git"
  - name: "https://github.com/sublimelsp/LSP-json.git"
  - name: "https://github.com/sublimelsp/LSP-dockerfile.git"
  - name: "https://github.com/sublimelsp/LSP-bash.git"
  - name: "https://github.com/sublimelsp/LSP-gopls.git"
    version: "main"
  - name: "https://github.com/sublimelsp/LSP-rust-analyzer.git"
    version: "main"
  - name: "https://github.com/sublimelsp/LSP-marksman.git"
    version: "main"
  - name: "https://github.com/sublimelsp/LSP-yaml.git"
  - name: "https://github.com/SublimeText/YamlPipelines.git"
  - name: "https://github.com/SublimeText/AFileIcon.git"
  - name: "https://github.com/SublimeText/Mermaid.git"
  - name: "https://github.com/SublimeText/Origami.git"
  - name: "https://github.com/SublimeText/Terraform.git"
  - name: "https://github.com/TerminalFi/LSP-copilot.git"
  - name: "https://github.com/titoBouzout/SideBarEnhancements.git"
    version: "st3"
 # Themes
  - name: "https://github.com/facelessuser/sublime-dracula-scheme.git"
  - name: "https://github.com/catppuccin/sublime-text.git"
    version: "main"