add_newline = false

format = """$username$hostname$directory$git_branch$git_metrics$git_status$cmd_duration$kubernetes$python$aws$docker_context$golang$java$memory_usage$nodejs$ruby$rust$package$line_break$character"""

[line_break]
disabled = true

[character]
success_symbol = "\n[❯](bold green)"
error_symbol = "\n[✖](bold red)"

[username]
disabled = false
show_always = false

[time]
disabled = true

[hostname]
ssh_only = true
format =  "[$hostname](bold green) "
ssh_symbol = " "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"
read_only = " "
read_only_style = "bold red"
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold yellow"

[git_metrics]
disabled = false
format = "([\\[](dimmed bold)[+$added]($added_style) [-$deleted]($deleted_style)[\\]](dimmed bold)) "

[git_status]
disabled = false
style = "bold yellow"
format = '([\[](bold dimmed)[$all_status$ahead_behind]($style)[\]](bold dimmed)) '

[cmd_duration]
min_time = 1000
format = "[$duration](bold yellow) "
show_milliseconds = false
show_notifications = false
min_time_to_notify = 10000

[aws]
symbol = "  "
format = '/ [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[docker_context]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[kubernetes]
disabled = false
format = '/ [ﴱ $context \($namespace\)](dimmed green) '
symbol = "ﴱ "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Fedora = " "
Linux = " "

[package]
disabled = true

[python]
disabled = false
symbol = " "
format = 'via [\(${symbol}:${pyenv_prefix}(${version}\) )(\($virtualenv\) )]($style)'

[ruby]
symbol = " "

[rust]
symbol = " "
